---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springtest
  namespace: default
  labels:
    app: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  template:
    metadata:
      labels:
        app: springtest
    spec:
      containers:
        - name: springtest
          image: "nikita9355/springtest:latest"
          ports:
            - containerPort: 8080

---
kind: Service
apiVersion: v1
metadata:
  name: springtest-service
  labels:
    env  : prod
    owner: BykovNV
spec:
  selector:
    app: springtest
  ports:
    - name      : app-listener
      nodePort  : 30036
      protocol  : TCP
      port      : 80
      targetPort: 8080 # Port on Pod
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: www.spring-testsber.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: springtest-service
              port:
                number: 80