---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springtest
  namespace: default
  labels:
    app: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  template:
    metadata:
      labels:
        app: springtest
    spec:
      containers:
        - name: springtest
          image: "nikita9355/springtest:latest"
          ports:
            - containerPort: 3000
