---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springtest
  namespace: default
  labels:
    project: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      project: springtest
  template:
    metadata:
      labels:
        project: springtest
    spec:
      containers:
        - name: springtest
          image: "nikita9355/springtest:latest"
          ports:
            - containerPort: 80

---
kind: Service
apiVersion: apps/v1
metadata:
  name: springtest-service
  labels:
    env  : prod
    owner: BykovNV
spec:
  selector:
    project: springtest
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80 # Port on Load Balancer
      targetPort: 80 # Port on Pod
  type: LoadBalancer

