---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: springtest
  namespace: default
  labels:
    app: springtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springtest
  template:
    metadata:
      labels:
        app: springtest
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: springtest
          image: "nikita9355/springtest:latest"
          ports:
            - containerPort: 8080
    readinessProbe:
      failureThreshold: 3
      httpGet:
        path: /-/ready
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 30
      periodSeconds: 5
      successThreshold: 1
      timeoutSeconds: 4

---
kind: Service
apiVersion: v1
metadata:
  name: springtest-service
  labels:
    env  : prod
    owner: BykovNV
spec:
  selector:
    app: springtest
  ports:
    - name      : app-listener
      nodePort  : 30030
      protocol  : TCP
      port      : 80
      targetPort: 8080 # Port on Pod
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
spec:
  rules:
  - host: www.spring-testsber.net
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: springtest-service
              port:
                number: 80